services:
  db:
    image: postgres
    ports:
    - "5435:5432"
    volumes:
      - com-db:/var/lib/postgresql/data1
    environment:
      - POSTGRES_DB=dproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
          bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  com-db:
    driver: local