# Generated by Django 3.2.6 on 2021-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210922_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
