# Generated by Django 3.2.6 on 2022-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(related_name='products', to='ecommerce.Brand'),
        ),
    ]
