# Generated by Django 3.2.6 on 2022-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_remove_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='ecommerce.Brand'),
        ),
    ]
