# Generated by Django 3.2.6 on 2022-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=127)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main-banner/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
