# Generated by Django 3.2.6 on 2022-12-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
