# Generated by Django 3.2.6 on 2022-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_product_sale_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
