# Generated by Django 3.2.6 on 2022-12-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_alter_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='until',
        ),
        migrations.RemoveField(
            model_name='product',
            name='validity',
        ),
    ]
