# Generated by Django 3.2.6 on 2022-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20221216_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=127)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
