# Generated by Django 3.2.6 on 2023-01-01 20:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
