# Generated by Django 3.2.6 on 2023-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='caption',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
