# Generated by Django 3.2.6 on 2023-01-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Completed'), (3, 'Cancel')], default=1),
        ),
    ]
